### ISSUE TITLE
用到的api接口是在哪里找到的？

### ISSUE THREAD

**Issue by eyingyang** [Yeuoly/YeuolyDanmuJi#7]
你好， bilibili的api接口可以在哪里打到呀？谢谢啦

**Comment by Yeuoly** [comment]
chrome或者edge的devtools里看网络模块，再通过搜索关键词寻找api，websocket接口看瀑布流长度



---原始邮件---
发件人: "eyingyang"<notifications@github.com&gt;
发送时间: 2020年9月22日(周二) 上午9:43
收件人: "Yeuoly/YeuolyDanmuJi"<YeuolyDanmuJi@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Yeuoly/YeuolyDanmuJi] 用到的api接口是在哪里找到的？ (#7)




 
你好， bilibili的api接口可以在哪里打到呀？谢谢啦

**Comment by eyingyang** [comment]
好的， 嘿嘿
